"""Module of wrapper classes."""
from improved_gym import error
from improved_gym.wrappers.atari_preprocessing import AtariPreprocessing
from improved_gym.wrappers.autoreset import AutoResetWrapper
from improved_gym.wrappers.clip_action import ClipAction
from improved_gym.wrappers.filter_observation import FilterObservation
from improved_gym.wrappers.flatten_observation import FlattenObservation
from improved_gym.wrappers.frame_stack import FrameStack, LazyFrames
from improved_gym.wrappers.gray_scale_observation import GrayScaleObservation
from improved_gym.wrappers.human_rendering import HumanRendering
from improved_gym.wrappers.normalize import NormalizeObservation, NormalizeReward
from improved_gym.wrappers.order_enforcing import OrderEnforcing
from improved_gym.wrappers.record_episode_statistics import RecordEpisodeStatistics
from improved_gym.wrappers.record_video import RecordVideo, capped_cubic_video_schedule
from improved_gym.wrappers.render_collection import RenderCollection
from improved_gym.wrappers.rescale_action import RescaleAction
from improved_gym.wrappers.resize_observation import ResizeObservation
from improved_gym.wrappers.step_api_compatibility import StepAPICompatibility
from improved_gym.wrappers.time_aware_observation import TimeAwareObservation
from improved_gym.wrappers.time_limit import TimeLimit
from improved_gym.wrappers.transform_observation import TransformObservation
from improved_gym.wrappers.transform_reward import TransformReward
from improved_gym.wrappers.vector_list_info import VectorListInfo
